language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run lint
after_success:
  - test $TRAVIS_BRANCH = "master" && npm run deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
